version: "3.9"
services:
  app:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm ci && npm start"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      HOST: "0.0.0.0"
